### PR TITLE
Adding Rule Based Config

### PR DESCRIPTION
**Pull request by kins-dev**
Adds support for rule based screen shots.  Not 100% complete, but it is getting close.  See todo.md for outstanding tasks.

In short, this takes the old config file format and brings it into a new format that allows much more flexibility in when, where and under what conditions a screenshot is taken.  User input is validated much more strictly and fixed up inputs are given back to the user so they can see what it should be.

A sample config file:
```json
{
  "SnapshotRules": [
    {
      "Name": "Unnamed Rule 1",
      "ZoomLevel": 0.25,
      "Directory": "Default",
      "FileName": "Default",
      "Trigger": {
        "Days": "Daily",
        "Weather": "Any",
        "Location": "Farm",
        "Key": "None",
        "StartTime": 600,
        "EndTime": 2600
      }
    },
    {
      "Name": "Unnamed Rule 2",
      "ZoomLevel": 1.0,
      "Directory": "/home/bob/SDV",
      "FileName": "Default",
      "Trigger": {
        "Days": "Daily",
        "Weather": "Any",
        "Location": "Farm",
        "Key": "None",
        "StartTime": 600,
        "EndTime": 2600
      }
    },
    {
      "Name": "Unnamed Rule 3",
      "ZoomLevel": 1.0,
      "Directory": "/home/bob/SDV",
      "FileName": "None",
      "Trigger": {
        "Days": "Daily",
        "Weather": "Any",
        "Location": "Any",
        "Key": "Multiply",
        "StartTime": 600,
        "EndTime": 2600
      }
    }
  ]
}
```

As I said this is not ready for prime time, maybe it should go onto a 2.0 branch.  But I wanted to update the base with my structure changes.

### CODE REVIEW

**Comment by kins-dev** [comment]
This is feature complete, I'm now going back to optimize things like the event hooks.

**Comment by kins-dev** [comment]
So I've finished running through test cases (included) as well as getting some user input.  I think this is good to go.

**Comment by kins-dev** [comment]
You should be able to test with [this](https://github.com/kins-dev/stardew-valley-daily-screenshot-mod/releases/tag/2.0.0_Testing)

**Comment by CompSciLauren** [comment]
Hey, this looks awesome! Thanks for linking the test-release file. I looked at everything and I really like all of these changes. The config is much easier to look at now from the player's perspective, and like you said it allows a lot more flexibility. I just need to finish updating documentation on the websites like Nexus, but I'll post the new release shortly after that. Terribly sorry that it took me so long to get to this. I've been ridiculously busy with my senior year at university and this was something I wanted to make sure I spent enough time looking at before moving forward. Thanks again for all your help with this, I think the players are going to love the new update!

**Comment by kins-dev** [comment]
No worries, I was a college student once, I understand having a life.  Like I said earlier, your code was easy and straight forward to work with.  That said, I hope some of the techniques I used make it in your daily life (e.g. use strong types to your advantage and support backwards compatibility).

**Comment by CompSciLauren** [comment]
For sure, I'll definitely continue to do my best and try to improve over time. Thanks again!

**Pull request merged**
